### ISSUE TITLE
controller undefined

### ISSUE THREAD

**Issue by benkamakorewa** [mixamo/control-scripts#1]
![mixamo - autocat](https://cloud.githubusercontent.com/assets/12145207/13088525/712993aa-d551-11e5-9e77-811fc2cf699e.JPG)
Hi Dan,

Love what you guys are doing at Mixamo.  I have been using Auto-Cat script and 3dsmax keeps pushing this error:

Welcome to MAXScript.

-- Error occurred in CATCreator(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 13231; line: 364
--  Frame:
--   CATRigPresetsDir: "C:\Users\faeben\AppData\Local\Autodesk\3dsMax\2015 - 64bit\ENU\plugcfg_ln\CAT\CATRigs\"-- Error occurred in CATCreator(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 13231; line: 364
--  Frame:
--   CATRigPresetsDir: "C:\Users\faeben\AppData\Local\Autodesk\3dsMax\2015 - 64bit\ENU\plugcfg_ln\CAT\CATRigs\"
--   spine1: undefined
--   numNeckBones: undefined
--   head: undefined
--   numFingersLeft: 5
--   neck1: undefined
--   newCAT: $Base Human
--   numFingersRight: 5
--   versinfo: dotNetClass:System.Diagnostics.FileVersionInfo
--   headEndBone: undefined
--   palm1: undefined
--   mixamoCharName: "mixamorig"
--   myFI: dotNetObject:System.Diagnostics.FileVersionInfo
--   palm2: undefined
--   mixamoCharHeight: undefined
--   CATHeight: undefined
--   versions: #("17", "0", "630", "0")
--   foot1: undefined
--   maxVersionNum: 17
--   foot2: undefined
--   called in autoCAT(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 23745; line: 677
--  Frame:
--   rightCATPlatform: undefined
--   hipsObj: undefined
--   leftFoot: undefined
--   rightArmRot: undefined
--   rightFoot: undefined
--   oldHipsPos: undefined
--   ang: undefined
--   CATObj: unsupplied
--   newCAT: undefined
--   oldLeftFootPos: undefined
--   needNamespacePrefixRemoval: false
--   oldRightFootPos: undefined
--   rightArm: undefined
--   minAngForIKFix: undefined
--   mixamoCharName: "mixamorig"
--   legRotAngles: undefined
--   meshObjs: #($default, $Eyelashes, $Body)
--   armBendAxis: undefined
--   helperObjs: #($mixamorig:Hips, $mixamorig:Spine, $mixamorig:Spine1, $mixamorig:Spine2, $mixamorig:Neck, $mixamorig:Head, $mixamorig:HeadTop_End, $mixamorig:RightEye, $mixamorig:LeftEye, $mixamorig:LeftShoulder, $mixamorig:LeftArm, $mixamorig:LeftForeArm, $mixamorig:LeftHand, $mixamorig:LeftHandMiddle1, $mixamorig:LeftHandMiddle2, $mixamorig:LeftHandMiddle3, $mixamorig:LeftHandMiddle4, $mixamorig:LeftHandThumb1, $mixamorig:LeftHandThumb2, $mixamorig:LeftHandThumb3, ...)
--   armBendAng: undefined
--   mixamoHips: undefined
--   leftArm: undefined
--   leftCATPlatform: undefined
--   leftArmRot: undefined
--   called in bnCreateCAT.pressed(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 27276; line: 785
--  Frame:
>> MAXScript Rollout Handler Exception:
-- Unknown property: "controller" in undefined <<

--   spine1: undefined
--   numNeckBones: undefined
--   head: undefined
--   numFingersLeft: 5
--   neck1: undefined
--   newCAT: $Base Human
--   numFingersRight: 5
--   versinfo: dotNetClass:System.Diagnostics.FileVersionInfo
--   headEndBone: undefined
--   palm1: undefined
--   mixamoCharName: "mixamorig"
--   myFI: dotNetObject:System.Diagnostics.FileVersionInfo
--   palm2: undefined
--   mixamoCharHeight: undefined
--   CATHeight: undefined
--   versions: #("17", "0", "630", "0")
--   foot1: undefined
--   maxVersionNum: 17
--   foot2: undefined
--   called in autoCAT(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 23745; line: 677
--  Frame:
--   rightCATPlatform: undefined
--   hipsObj: undefined
--   leftFoot: undefined
--   rightArmRot: undefined
--   rightFoot: undefined
--   oldHipsPos: undefined
--   ang: undefined
--   CATObj: unsupplied
--   newCAT: undefined
--   oldLeftFootPos: undefined
--   needNamespacePrefixRemoval: false
--   oldRightFootPos: undefined
--   rightArm: undefined
--   minAngForIKFix: undefined
--   mixamoCharName: "mixamorig"
--   legRotAngles: undefined
--   meshObjs: #($Male_Body_HighPoly)
--   armBendAxis: undefined
--   helperObjs: #($mixamorig:Hips, $mixamorig:Spine, $mixamorig:Spine1, $mixamorig:Spine2, $mixamorig:Neck, $mixamorig:Head, $mixamorig:HeadTop_End, $mixamorig:LeftShoulder, $mixamorig:LeftArm, $mixamorig:LeftForeArm, $mixamorig:LeftHand, $mixamorig:LeftHandThumb1, $mixamorig:LeftHandThumb2, $mixamorig:LeftHandThumb3, $mixamorig:LeftHandThumb4, $mixamorig:LeftHandIndex1, $mixamorig:LeftHandIndex2, $mixamorig:LeftHandIndex3, $mixamorig:LeftHandIndex4, $mixamorig:LeftHandMiddle1, ...)
--   armBendAng: undefined
--   mixamoHips: undefined
--   leftArm: undefined
--   leftCATPlatform: undefined
--   leftArmRot: undefined
--   called in bnCreateCAT.pressed(); filename: C:\Users\faeben\Downloads\AutoCAT\AutoCAT\AutoCAT.ms; position: 27276; line: 785
--  Frame:
>> MAXScript Rollout Handler Exception:
-- Unknown property: "controller" in undefined <<

**Comment by danbabcock3d** [comment]
Hi Ben,
I don't think I've every gotten a ticket email from github before lol.
First, lets do the sanity check stuff - the scripts aren't meant to take into account every situation, so lets double check the basics:

**-Clean scene, nothing in it
-Settings reset to default**
-bring in character
-Use AutoCAT Script


If you still hit an issue after double checking with this workflow, I'll need to see the character fbx file to troubleshoot.

**Comment by benkamakorewa** [comment]
Hi Dan,
Thanks for that, worked great.
